/**
 * TCREI Validation Utilities
 * Task, Context, Reference, Evaluation, Input
 */

export function generateResearchDoc(tcrei) {
  const timestamp = new Date().toISOString();
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return `# Research: ${tcrei.task}

**Created**: ${date}
**Status**: In Progress

---

## TCREI Validation

### Task
${tcrei.task}

### Context
${tcrei.context}

### Reference
${tcrei.reference}

### Evaluation
${tcrei.evaluation}

### Input
${tcrei.input}

---

## Research Findings

*[Use this section to document your research findings]*

- [ ] Read relevant files
- [ ] Verify assumptions
- [ ] Document patterns found
- [ ] List unknowns or questions

---

## Verified Claims

*[Add verified claims with file:line references]*

**Example:**
- ✓ User model defined in \`src/models/user.ts:15-42\`
- ✓ Authentication uses JWT tokens (verified in \`auth.ts:89\`)

---

## Confidence Assessment

**Overall Confidence**: __%

**Breakdown:**
- Task understanding: __%
- Technical approach: __%
- Resource availability: __%
- Time estimation: __%

---

## Next Steps

- [ ] Complete research investigation
- [ ] Verify all claims with sources
- [ ] Create implementation plan
- [ ] Get approval to proceed

---

**Generated by drewsky CLI** | [Documentation](https://github.com/drewbeyersdorf/agent-improvement-techniques)
`;
}

export function validateTCREI(tcrei) {
  const errors = [];

  if (!tcrei.task || tcrei.task.trim().length === 0) {
    errors.push('Task is required');
  }

  if (!tcrei.context || tcrei.context.trim().length === 0) {
    errors.push('Context is required');
  }

  if (!tcrei.evaluation || tcrei.evaluation.trim().length === 0) {
    errors.push('Evaluation criteria are required');
  }

  if (!tcrei.input || tcrei.input.trim().length === 0) {
    errors.push('Input requirements are required');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}
